language: node_js
node_js:
- node
dist: trusty
addons:
  apt:
    packages:
    - rpm
before_install:
  - gem install package_cloud
  - gem install fpm
script:
- VERSION_NUMBER=$(cat package.json | jq -r '.version')
- npm run build-deb
- mkdir -p packages/deb
- mkdir -p packages/rpm
- mv mc-cli_${VERSION_NUMBER}_all.deb packages/deb/mc-cli_${VERSION_NUMBER}-${TRAVIS_BUILD_NUMBER}_all.deb
- fpm -s npm -t rpm minecraft-cli
- mv node-minecraft-cli-*.rpm packages/rpm/
deploy:
- provider: s3
  access_key_id: AKIAJJENKP3U6XBQVGLA
  secret_access_key:
    secure: mqdIq9lise/jvNLGTB3+W+bN2KJkRGMEGPeMu2N01wsa3vkdcEEiMMX/Yegkr2iZB+KhZDCrD8XE/yqiiM0xELhWwrWfUB4O4BfmRgcbpQo046X34uGhthnYeZqo9jhqcvLBpvlAQrlWJ0IOM6HsBkicJ0GZ8hnu162do3//H5rWLXFK+htryD8UitHp0N5AyHYrgPUdkeZog930yGmOxZ/kTeF+snstkFwXSuoj/m9yWPiP8HE1vnvFTHw8APfVt4OqX25iDeZVyXw0rI3rDrmtj1Acrx+20NN5wIltjxmm+76LKP8xCbmkvH3JSTOCjRSwY/7tDxB3jZ7WUJBGQPgstUg92oQFxVY6xQlD953UtO/zrocm67cDkYD9Z4wsCcDk15ElNItygK4+HKdw0fshM7WJTNtuLJaaH/X86sqUUJP6yL9b5l9EHQojZ0DfMywU/vuujkkV5OCynhdUNU4GgvZjARk0sA1rD1kNX/A9hsu+fFhu1WsnKi57Eh89e9gGmXERBXE2O9gwQXEEXkMv15WRTmmbC2PPLM1wtrQ8RETGyc+6WJzD5nyvUUHlwyBl/eIbT7qPxFvf7vOW0HyfQGzKfJMqD7PJEbsx7M9vF0IeyjubPi/QJw3bYE6ze73f6fhZQW211RlEN9xi5PuiMujQ9u6HJVMZFkpcMMM=
  bucket: artifacts.filiosoft.com
  local-dir: "packages"
  upload-dir: mc-cli
  acl: public_read
  skip_cleanup: true
  on:
    repo: HexagonMinecraft/mc-cli
- provider: script
  script: bash scripts/packagecloud-deploy.sh
  on:
    tags: true
    all_branches: false
