language: go
go:
- 1.8.x
dist: trusty
sudo: required
before_install:
- openssl aes-256-cbc -K $encrypted_6e849d71586b_key -iv $encrypted_6e849d71586b_iv - in private.key.enc -out private.key -d
before_script:
- sudo sh -c 'echo "deb http://repo.aptly.info/ squeeze main" >> /etc/apt/sources.list'
- sudo apt-key adv --keyserver keys.gnupg.net --recv-keys 9E3E53F19C7DE460
- wget -qO - https://www.aptly.info/pubkey.txt | sudo apt-key add -
- sudo apt-get -qq update
- sudo apt-get install equivs aptly
script:
- bash scripts/build.sh
deploy:
    - provider: s3
      access_key_id: AKIAIJT6AK44UZASIF3Q
      secret_access_key: 
          secure: hrYA9PnRD/1/np82EiTbO0+Yeuc2B0TtWkgiyV2JkSzeCYWIosjrx3te6CGPk7zKVFtV3tICCh84h2YN2J5eua89esxBNJm5oMe+gT0iuMgDnn1blO+JH78Sdf4j93W6R2Z9TDVdySHaQ/zhM908mVIWPH0Vq4KgH/ntg4j6jkwhAFlFOFOdAbxObSRcylOtOzmIi+bAiU6Wpkeip6SkYRvJp/fxzKYNSR5axefvrQnSb4M605a+YcKP3kw7ggXFciImKUEQIukcZIWUOlUp80mIuwpNhIK8jFTsGFmhwY57wJ8VmavyL/BOAPGgdRsfrHkWaADT9dRYNPsOtJH7pZ1BaKeWDaIdRMSgCkceOMh2aldtFNR46cNdFpMSbXn3lA39prcCUS72UJ4Zk5TuU9v+6M7iEQkJ2sEadVrqFzNOMyAnp/rHvGyvoAAjhPLNqjunWNxsBfxUcgFaz+Q/rUNZ9tz9TpC8snzNS9GMQrXSM010QSsE+MALkfRPTTIqRUC+9k0gn+/f5L96boZFQiruy05k2Oo2Yw/WX4xx36ynfcsiTtBF0AQobe0dfQ439U64gtNjliQw+nJpX3sqLVz1f/Dr3+6SVsDyRwVmz/vh2LxhbZYIUX8gb3NSTvZ2HklybTFRkNAayYg6KRE3jqvOPPh+jZtiK6Z9z37uO+Y=
      bucket: artifacts.filiosoft.com
      local-dir: "bin"
      upload-dir: mcpr-cli
      acl: public_read
      skip_cleanup: true
      on:
        branch: master
    - provider: releases
      api_key:
        secure: fCkR5bKDQTfo1iUWE0PMh+8z265U83kSSihMSgj1x/9gcAXWK6InVekdkc2PIuJHceGQMKRwhJP4PV50GNofGk3QxO8/aYAGn7+efjZ2KgEXgZ1Tlq7uEom1zbkUu0yQj9Q1DmrMMTrQXBlXS74CKylPM42zgLb6qg+McSF6gcGYDYBHOYguh1wvDOlJAjafhaMy4J/mnVp1ca1QS1SVevSHG/VCV0OLIDSxysxFVgj9ZHrMnPzs9FAcuIqfGeSjaqXAVXygYRhJntGPSwResq313C8bDKgGbJo6GOWIBBbVgjQhKDLu3AIqnCxhUkl86WF2vPXnsWqdqPOmne2W32VD6gxvWnxb7/gfjK6zOPqhZO30ky6Dhh/Yi1QSuRhNOMalIRjLxKkl06VC9QED39TkJKZXeHLIZb/LYC9ICSJ5eEFgd2oj1tpWrbo1DDG99S4JhWstHDrqY4QzbQOvFM57L6QypFMsdDjF+jIT3jICcfCN9ObhOcgx4JRWKZ6L/5IsI3G/G+Cvc40inyawxKJq84jbUD/8pQrerR2vzxizAG8RcuFFpZN+xlYReFXkT/qzmMLBVBcue/YGdz5qaTjp51MEXvf+gWB+TsD6ocho41k8Hgwy6XkGSv7lJ8CmqpQXjLpwmSEWpdW7VREQqLBJfnjv1A68Yo+zDfcp7v4=
      file_glob: true
      file: bin/**/mcpr-v*
      skip_cleanup: true
      on:
        tags: true
        repo: mcpr/mcpr-cli