language: go
go:
  - 1.8.x
dist: trusty
install:
 - go get github.com/Masterminds/semver
 - go get github.com/briandowns/spinner
 - go get github.com/urfave/cli
 - mkdir -p packages/linux
 - mkdir -p packages/darwin
 - mkdir -p packages/windows
script:
- echo "Building Linux"
- go build
- cp mc-cli packages/linux/mc-$TRAVIS_BUILD_NUMBER
- mv mc-cli packages/linux/mc
- echo "Building Darwin"
- GOOS=darwin go build
- cp mc-cli packages/darwin/mc-$TRAVIS_BUILD_NUMBER
- mv mc-cli packages/darwin/mc
- echo "Building Windows"
- GOOS=windows go build
- cp mc-cli.exe packages/windows/mc-$TRAVIS_BUILD_NUMBER.exe
- mv mc-cli.exe packages/windows/mc.exe
deploy:
- provider: s3
  access_key_id: AKIAJJENKP3U6XBQVGLA
  secret_access_key:
    secure: mqdIq9lise/jvNLGTB3+W+bN2KJkRGMEGPeMu2N01wsa3vkdcEEiMMX/Yegkr2iZB+KhZDCrD8XE/yqiiM0xELhWwrWfUB4O4BfmRgcbpQo046X34uGhthnYeZqo9jhqcvLBpvlAQrlWJ0IOM6HsBkicJ0GZ8hnu162do3//H5rWLXFK+htryD8UitHp0N5AyHYrgPUdkeZog930yGmOxZ/kTeF+snstkFwXSuoj/m9yWPiP8HE1vnvFTHw8APfVt4OqX25iDeZVyXw0rI3rDrmtj1Acrx+20NN5wIltjxmm+76LKP8xCbmkvH3JSTOCjRSwY/7tDxB3jZ7WUJBGQPgstUg92oQFxVY6xQlD953UtO/zrocm67cDkYD9Z4wsCcDk15ElNItygK4+HKdw0fshM7WJTNtuLJaaH/X86sqUUJP6yL9b5l9EHQojZ0DfMywU/vuujkkV5OCynhdUNU4GgvZjARk0sA1rD1kNX/A9hsu+fFhu1WsnKi57Eh89e9gGmXERBXE2O9gwQXEEXkMv15WRTmmbC2PPLM1wtrQ8RETGyc+6WJzD5nyvUUHlwyBl/eIbT7qPxFvf7vOW0HyfQGzKfJMqD7PJEbsx7M9vF0IeyjubPi/QJw3bYE6ze73f6fhZQW211RlEN9xi5PuiMujQ9u6HJVMZFkpcMMM=
  bucket: artifacts.filiosoft.com
  local-dir: "packages"
  upload-dir: mc-cli
  acl: public_read
  skip_cleanup: true
  on:
    branch: go
    repo: HexagonMinecraft/mc-cli
