language: go
matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      dist: trusty
      sudo: required
      go:
      - 1.8.x
    - os: osx
      language: ruby
      osx_image: xcode9
install:
- bash scripts/travis-install.sh
script: 
- export GOPATH=$(pwd)/go
- export PATH=$PATH:$GOPATH/bin
- cd go/src/github.com/mcpr/mcpr-cli
- ls
- bash scripts/build.sh
deploy:
  - provider: s3
    access_key_id: AKIAIJT6AK44UZASIF3Q
    secret_access_key: 
      secure: C2Gr1XfpVdMscoBydXCg6PZDY6TBqFLvdSd/NnZCqhRlpBN9qMbT2xs69ucsxc/lAfappZCPrTM2RQj0ORBWzZjrLOZsczH4TZra4MmJ0PXPxGds72/zI1WjcRGYchlFR8aTmHNqls7eI6xmM6KHgWNMhFw4zE5Bf/8DxtMwzlN2do+RBdbOIYd0tPPksjlA2zi/wjEkj0ZKo/fQB5qCdIJSevrOzZhkQt/zUwJ6bMXfwp6/DvQpMEvH4J4lkXQtzYBBm0dJFBXxfKG9cqO5xfkfpxPSXQJT/oNu8hj/AYZHjdp6klYJnqpB+HJHj8lNiFSwh2OccL64I6igTataDEvrDNa7+WzPfqizL/ZsPlhWqYNW4myhIsi8IUXhj3hJGf8L2qZgclxYOEprWFe3whFpwjXGkcVMwQ67fuf6isjYrKnH2d5+XeIN9OUyPl8WFNv04jWJPN4P3Ky+Vlx3jltyU50A+wvzAyuERXzoCBrf9ezm0WjpbFFlVvJlCTiOw89qD9mtVCAVBaFX//suTKo+kIirXYGpYQboHIIt713YGVAj2pHft4WocyGD2IlvI9ZPzPKlDHfZW3hotyqnl9wTEjTUasmpGOHBN6j6DPcX1XPzr/kpL/+os12A40ASKNaKBuKx4y/CdvFvNTRFVdViaRg9od5atwpPDmyfZI0=
    bucket: artifacts.filiosoft.com
    local-dir: bin
    upload-dir: mcpr-cli
    acl: public_read
    skip_cleanup: true
    on:
      branch: master
  - provider: s3
    access_key_id: AKIAIJT6AK44UZASIF3Q
    secret_access_key: 
      secure: C2Gr1XfpVdMscoBydXCg6PZDY6TBqFLvdSd/NnZCqhRlpBN9qMbT2xs69ucsxc/lAfappZCPrTM2RQj0ORBWzZjrLOZsczH4TZra4MmJ0PXPxGds72/zI1WjcRGYchlFR8aTmHNqls7eI6xmM6KHgWNMhFw4zE5Bf/8DxtMwzlN2do+RBdbOIYd0tPPksjlA2zi/wjEkj0ZKo/fQB5qCdIJSevrOzZhkQt/zUwJ6bMXfwp6/DvQpMEvH4J4lkXQtzYBBm0dJFBXxfKG9cqO5xfkfpxPSXQJT/oNu8hj/AYZHjdp6klYJnqpB+HJHj8lNiFSwh2OccL64I6igTataDEvrDNa7+WzPfqizL/ZsPlhWqYNW4myhIsi8IUXhj3hJGf8L2qZgclxYOEprWFe3whFpwjXGkcVMwQ67fuf6isjYrKnH2d5+XeIN9OUyPl8WFNv04jWJPN4P3Ky+Vlx3jltyU50A+wvzAyuERXzoCBrf9ezm0WjpbFFlVvJlCTiOw89qD9mtVCAVBaFX//suTKo+kIirXYGpYQboHIIt713YGVAj2pHft4WocyGD2IlvI9ZPzPKlDHfZW3hotyqnl9wTEjTUasmpGOHBN6j6DPcX1XPzr/kpL/+os12A40ASKNaKBuKx4y/CdvFvNTRFVdViaRg9od5atwpPDmyfZI0=
    bucket: artifacts.filiosoft.com
    local-dir: bin
    upload-dir: mcpr-cli
    acl: public_read
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key:
      secure: fCkR5bKDQTfo1iUWE0PMh+8z265U83kSSihMSgj1x/9gcAXWK6InVekdkc2PIuJHceGQMKRwhJP4PV50GNofGk3QxO8/aYAGn7+efjZ2KgEXgZ1Tlq7uEom1zbkUu0yQj9Q1DmrMMTrQXBlXS74CKylPM42zgLb6qg+McSF6gcGYDYBHOYguh1wvDOlJAjafhaMy4J/mnVp1ca1QS1SVevSHG/VCV0OLIDSxysxFVgj9ZHrMnPzs9FAcuIqfGeSjaqXAVXygYRhJntGPSwResq313C8bDKgGbJo6GOWIBBbVgjQhKDLu3AIqnCxhUkl86WF2vPXnsWqdqPOmne2W32VD6gxvWnxb7/gfjK6zOPqhZO30ky6Dhh/Yi1QSuRhNOMalIRjLxKkl06VC9QED39TkJKZXeHLIZb/LYC9ICSJ5eEFgd2oj1tpWrbo1DDG99S4JhWstHDrqY4QzbQOvFM57L6QypFMsdDjF+jIT3jICcfCN9ObhOcgx4JRWKZ6L/5IsI3G/G+Cvc40inyawxKJq84jbUD/8pQrerR2vzxizAG8RcuFFpZN+xlYReFXkT/qzmMLBVBcue/YGdz5qaTjp51MEXvf+gWB+TsD6ocho41k8Hgwy6XkGSv7lJ8CmqpQXjLpwmSEWpdW7VREQqLBJfnjv1A68Yo+zDfcp7v4=
    file_glob: true
    file: bin/**/mcpr-*
    skip_cleanup: true
    on:
      tags: true
      repo: mcpr/mcpr-cli